### ISSUE TITLE
README.md references non-public link

### ISSUE THREAD

**Issue by jbeich** [freebsd/chromium#2]
[Google will no longer accept FreeBSD/OpenBSD patches](https://groups.google.com/a/chromium.org/g/chromium-dev/c/b57hDs8yE4g/m/4yppcLc9BQAJ) leads to a login page, requiring a Google Account.

**Comment by Jehops** [comment]
Ugh.  It's a long discussion that is hosted on Google Groups.  Maybe we can host it elsewhere.

**Comment by jbeich** [comment]
In the past I've checked for new discussions via https://groups.google.com/a/chromium.org/forum/#!searchin/chromium-dev/freebsd|sort:date

**Comment by jbeich** [comment]
I'm interested primarily because of
https://bugzilla.mozilla.org/show_bug.cgi?id=1498302#c1
https://lists.freebsd.org/pipermail/freebsd-chromium/2018-March/003376.html

**Comment by Jehops** [comment]
Those are the same discussions.  I have no idea why one URL would be public, but the other private.  In any case, I just used the URL you provided.
